export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_TODOS: 'SET_TODOS',
	DELETE_TODOS: 'DELETE_TODOS',
	ADD_COMMENT: 'ADD_COMMENT',
	DELETE_COMMENT: 'DELETE_COMMENT',
	UPDATE_TODOS: 'UPDATE_TODOS',
};
